### ISSUE TITLE
Movie Info links

### ISSUE THREAD

**Issue by brentmclark** [RonWaller/movie_details_netlify#1]
If I'm reading the code below correctly, you're registering a global event handler for `click` and using it to determine if the user clicked on the `more info` "button".  If they have, you grab the associated movie id, set it in session storage, navigate them to the individual movie page, and use the current sessionStorage value to determine which movie to show.

Although this process clearly works, seeing this during a code review would give me some concern.  Can you share with me the background on why you went with this approach over something like an `<a>` tag and a `queryString` param?

https://github.com/RonWaller/movie_details_netlify/blob/aa2e528275213629173b91884325ce4c6d69cafa/build/js/main.js#L58-L64

**Comment by RonWaller** [comment]
I am using Local Storage to grab the movie ID for the "more info" button that was clicked. I am using a separate JS file to create the "details" of the movie that was selected. TMDB api uses a different api url for the movie details information. I received some assistance and this was the suggestion so that I could have access to the movie ID and use it in my API call in a separate. Hope this answers your question.

**Comment by brentmclark** [comment]
That makes sense.  Making the jump from JS file to JS file is certainly a challenge.  I assume you're referring to this line of code in the `movie_details.js` file?

https://github.com/RonWaller/movie_details_netlify/blob/master/build/js/movie_details.js#L7

**Comment by RonWaller** [comment]
Yes, That is where I am grabbing the ID from the other JS file so I can use it.

**Comment by brentmclark** [comment]
One alternative that invlves less JavaScript, and would therefore create a smaller surface area for bugs, would be to use an `<a>` tag and a `queryString` param as I suggested.  Then, on the destination page (with the new JS file) you could grab the `queryString` param off the URL like so:

``` javascript
const urlParams = new URLSearchParams(window.location.search);
const movieId = urlParams.get('movie_id');
```

**Comment by RonWaller** [comment]
Made the change to anchor tags instead of local storage and it works. YES!!!
