### ISSUE TITLE
Reconsider fetch function

### ISSUE THREAD

**Issue by brentmclark** [RonWaller/movie_details_netlify#2]
The function responsible for fetching the movies is clearly working, but the way it's currently implemented won't work well in certain cases.  For example, if you wanted to control the pagination or add filtering – currently handled with a `slice(50,10)` – you'll have a hard time.  

What are your thoughts on reworking this method to decouple the fetch code from the pagination code?

https://github.com/RonWaller/movie_details_netlify/blob/f90574815a7b6e0fddda717c5cf26e02b8804807/build/js/main.js#L15-L28

**Comment by RonWaller** [comment]
My goal was to just have 50 movies and each page you only get 20 movies. I could implement pages. There are thousands of movie just 20 at a time.
