### ISSUE TITLE
Consider replacing custom event handler with anchor tag

### ISSUE THREAD

**Issue by brentmclark** [RonWaller/movie_details_netlify#3]
The code below is another example of using a custom event handler to do what an `<a>` tag does for free.  This is a great pattern to look for in your code and update to using the raw power of HTML instead of The JavaScipt Hammer:tm:.

https://github.com/RonWaller/movie_details_netlify/blob/f90574815a7b6e0fddda717c5cf26e02b8804807/build/js/movie_details.js#L12-L16

**Comment by RonWaller** [comment]
Think I was having issue with click events on dynamic html and the timing of it loading. Not sure why I didnt put in anchor tags.

**Comment by RonWaller** [comment]
Created new branch. Made changes to Go Back link to an anchor tag. Submitted a Pull Request

**Comment by RonWaller** [comment]
Change was fixed and merged with #2
